version: '3.7'

services:
  adminer:
    image: "adminer:${ADMINER_VERSION}"
    env_file:
      - .env.adminer

  mariadb:
    image: "mariadb:${MARIADB_VERSION}"
    env_file:
      - .env.mariadb
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=${TIME_ZONE}"
    volumes:
      # - /vagrant/docker/mariadb/data:/var/lib/mysql
      - mariadb-data-volume:/var/lib/mysql
      - /vagrant/docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - /vagrant/docker/mariadb/sql:/docker-entrypoint-initdb.d

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    env_file:
      - .env.postgres
    command: "-c 'config_file=/etc/postgresql/postgresql.conf'"
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      # - /vagrant/docker/postgres/data:/var/lib/postgresql/data
      - postgres-data-volume:/var/lib/postgresql/data
      - /vagrant/docker/postgres/sql:/docker-entrypoint-initdb.d
      - /vagrant/docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
  mariadb-data-volume:
    driver: local
  postgres-data-volume:
    driver: local
